import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Footer, Header } from './components'
import { AdditionalThemeProvider } from './providers'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Błżej Bryła - Portfolio',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AdditionalThemeProvider>
          <Header />
          {children}
          <Footer />
        </AdditionalThemeProvider>
      </body>
    </html>
  )
}
